import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title>Hello World</Title>
    </div>
  );
}

const Title = styled.h1`
  background: lightgray;
  padding: 2rem;
  border: 2px solid gray;
`;
