import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title className="text-3xl underline">Hello World</Title>
    </>
  );
};

export default Home;

const Title = styled.h1`
  background: lightgray;
  padding: 2rem;
  border: 2px solid gray;
`;
